
services:
  timescale:
    container_name: ega-timescaledb
    image: timescale/timescaledb:latest-pg13
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    restart: always